version: '2'
services:
    zoo1:
        image: zookeeper
        restart: always
        ports:
            - 2181:2181
        environment:
            ZOO_MY_ID: 1
            ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888

    zoo2:
        image: zookeeper
        restart: always
        ports:
            - 2182:2181
        environment:
            ZOO_MY_ID: 2
            ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888

    zoo3:
        image: zookeeper
        restart: always
        ports:
            - 2183:2181
        environment:
            ZOO_MY_ID: 3
            ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888

    consul:
        image: qnib/consul
        container_name: consul
        ports:
            - 9002:8500
        environment:
         - DC_NAME=qnib
         - RUN_SERVER=true
         - BOOTSTRAP_CONSUL=true
        dns: 127.0.0.1
        privileged: true

    zkui:
        hostname: zkui
        container_name: zkui
        image: qnib/zkui
        dns: 127.0.0.1
        dns_search:
         - node.consul
         - service.consul
        environment:
         - DC_NAME=qnib
         - ZKUI_ZK_SERVER=zoo1:2181,zoo2:2181,zoo3:2181
        links:
         - zoo1:zoo1
        links:
         - zoo2:zoo2
        links:
         - zoo3:zoo3
        links:
         - consul:consul
        ports:
           - 9001:9090
        privileged: true


    kafka1:
        image: wurstmeister/kafka
        restart: always
        ports:
            - 9091:9092
        environment:
          - KAFKA_ADVERTISED_HOST_NAME=172.19.36.147
          - KAFKA_ADVERTISED_PORT=9091
          - KAFKA_ZOOKEEPER_CONNECT=zoo1:2181,zoo2:2181,zoo3:2181
          - KAFKA_BROKER_ID=1
        links:
         - zoo1:zoo1
        links:
         - zoo2:zoo2
        links:
         - zoo3:zoo3
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock


    kafka2:
        image: wurstmeister/kafka
        restart: always
        ports:
            - 9092:9092
        environment:
          - KAFKA_ADVERTISED_HOST_NAME=172.19.36.147
          - KAFKA_ADVERTISED_PORT=9092
          - KAFKA_ZOOKEEPER_CONNECT=zoo1:2181,zoo2:2181,zoo3:2181
          - KAFKA_BROKER_ID=2
        links:
         - zoo1:zoo1
        links:
         - zoo2:zoo2
        links:
         - zoo3:zoo3
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock



    kafka3:
        image: wurstmeister/kafka
        restart: always
        ports:
            - 9093:9092
        environment:
          - KAFKA_ADVERTISED_HOST_NAME=172.19.36.147
          - KAFKA_ADVERTISED_PORT=9093
          - KAFKA_ZOOKEEPER_CONNECT=zoo1:2181,zoo2:2181,zoo3:2181
          - KAFKA_BROKER_ID=3
        links:
         - zoo1:zoo1
        links:
         - zoo2:zoo2
        links:
         - zoo3:zoo3
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock



    kafka-offset-monitor:
        image: jpodeszwik/kafka-offset-monitor
        ports:
            - 9011:8080
        environment:
         - ZK=zoo1:2181,zoo2:2181,zoo3:2181
        links:
         - zoo1:zoo1
        links:
         - zoo2:zoo2
        links:
         - zoo3:zoo3

    kafka-manager:
        image: sheepkiller/kafka-manager
        ports:
            - 9012:9000
        environment:
         - ZK_HOSTS=zoo1:2181,zoo2:2181,zoo3:2181
         - APPLICATION_SECRET=letmein
        links:
         - zoo1:zoo1
        links:
         - zoo2:zoo2
        links:
         - zoo3:zoo3
